#!/bin/sh
export HOSTNAME=linux
export USER=root
export HOME=/home
export PS1="[$USER@$HOSTNAME \W]\# "
PATH=$PATH:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin
LD_LIBRARY_PATH=/lib:/usr/lib:$LD_LIBRARY_PATH
export PATH LD_LIBRARY_PATH
